addons:
  apt:
    packages:
      - google-chrome-stable
    sources:
      - google-chrome
cache:
  directories:
    - ./node_modules/
    - ./third_party/
    - ./tools/
dist: trusty
install: true
language: python
python:
- 2.7
sudo: required

branches:
  only:
  - master
before_install:
- pip install --upgrade pip
- pip install codecov
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bash scripts/run_karma_tests.sh --single-run --enable-coverage
- bash scripts/run_linter.sh
- bash scripts/run_e2e_tests.sh
after_success:
- codecov --file ./karma_coverage_reports/coverage-final.json
